---
title: "Haoran-draft"
author: "Haoran Yan"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 0. Load the libraries

```{r}
#Load the packages
library(dplyr)  
library(ggplot2)
library(tidyr)
library(tidyverse)
library(caret)
library(caTools)
```

# 1. Import the data

```{r}
dataset <- read.csv("C:/Users/18056/Documents/GitHub/vignette-SVM-KNN/data/heart.csv")
head(dataset)
```

# 2. Data Cleaning


```{r}
#classify the variables into categorical and numerical variables 
#select the numerical variables
numeric_var <-dataset %>% 
  select("age","trtbps","chol","thalachh","oldpeak")
#select the categorical values 
categorical_var<- dataset %>%
  select("sex","cp","fbs","restecg","exng","slp","caa",
         "thall","output")%>%
  mutate_if(is.numeric, as.factor)

#combine the categorical  and numerical values
dataset1 = cbind(categorical_var,numeric_var)
```

```{r}
head(dataset1)
```

```{r}
df_outliers<-as.data.frame(dataset1 %>%
                  select("trtbps","thalachh","chol","oldpeak"))
```


```{r}
outliers <- function(x) { 
 #IQR
  Q1 <- quantile(x, probs=.25) 
  Q3 <- quantile(x, probs=.75) 
  iqr = Q3-Q1 
 
 #Upper Range
 upper_limit = Q3 + (iqr*1.5) 
 #Lower Range Eliminating Outliers 
 lower_limit = Q1 - (iqr*1.5) 
 
 x > upper_limit | x < lower_limit 
} 
# remove the outliers
remove_outliers <- function(df_outliers, cols = names(df_outliers)) { 
  for (col in cols) { 
    df_outliers<- df_outliers[!outliers(df_outliers[[col]]),] 
  } 
  df_outliers 
}
# we have removed the outliers from the selected features 
# create new dataset without outliers
dataset2<-remove_outliers(dataset1,c("trtbps","oldpeak" ,"thalachh", "chol"))
```



# 3. Feature Selection

```{r}
set.seed(100)
#create the subsets for sizes
subsets <- c(1:8,10,13)
# define the control using random forest selection 
ctrl <- rfeControl(functions = rfFuncs,
                   method = "repeatedcv",
                   repeats = 5,
                   number = 10,
                   verbose = FALSE)

#run the RFE
results <- rfe(x=dataset2[, c(1:8,10:14)], y=dataset2$output,
                 sizes = subsets,
                 rfeControl = ctrl)

# Print the selected features
print(predictors(results))
```

# 4. Split the data

```{r}
set.seed(100)
data1 <- dataset2 %>%
  select(predictors(results), "output")
head(data1)
```

```{r}
set.seed(100)
intrain <- createDataPartition(y = data1$output, p= 0.7, list = FALSE)
training <- heart[intrain,]
testing <- heart[-intrain,]

training[["output"]] = factor(training[["output"]])

head(training)
```

# 5. Construct the model

```{r}
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)

svm_Linear <- train(output ~., data = training, method = "svmLinear",
trControl=trctrl,
preProcess = c("center", "scale"),
tuneLength = 10)

svm_Linear
```
# 6. Make prediction

```{r}
test_pred <- predict(svm_Linear, newdata = testing)
test_pred
```

```{r}
caret::confusionMatrix(table(test_pred, testing$output))
```


